"""add column category

Revision ID: 280255479288
Revises: 49598d87fa53
Create Date: 2023-05-28 17:31:05.766681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280255479288'
down_revision = '49598d87fa53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), server_default='post', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
