"""add banner field

Revision ID: dcd4ec75756f
Revises: 280255479288
Create Date: 2023-05-28 18:02:55.429760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd4ec75756f'
down_revision = '280255479288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('banner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'banner')
    # ### end Alembic commands ###
